### PR TITLE
Update 09-08-19-frontend-development.md

### PR DESCRIPTION
**Pull request by josephpal13**
I've added the link on the Additional Resources section of your post per Darwin Biler's instructions.

### CODE REVIEW

**Comment by buonzz** [comment]
hi @josephpal13 thanks for this :)
but i think this could be more relevant into "Other Useful Resources"  section
http://www.laravelbestpractices.com/#other_resources
instead of "Frontend Development"?

**Comment by josephpal13** [comment]
Hi Darwin,

Sure thing, yes please thatwould be perfect!

Thanks!
Joseph

**Comment by josephpal13** [comment]
Hi Darwin,

Please confirm if I need to send in another pull request for this.

Cheers!
Joseph

**Comment by josephpal13** [comment]
Dear Darwin,

Was wondering if you needed any more information from my end to make this
happen?

**Comment by buonzz** [comment]
sorry for the delay this is now merged

**Comment by josephpal13** [comment]
Hey Darwin,

That's awesome! Thank you so much.

**Pull request merged**
